"""Add promotion_text column to Product

Revision ID: 03034c138132
Revises: b1791df9a769
Create Date: 2024-07-06 12:01:43.871961

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '03034c138132'
down_revision = 'b1791df9a769'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.add_column(sa.Column('promotion_text', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_column('promotion_text')

    # ### end Alembic commands ###
